### ISSUE TITLE
discs are stereo big nono

### ISSUE THREAD

**Issue by Redd56** [SuperNoobYT/AllTheFanMadeDiscs#1]
some of the music discs are in stereo which is a big nono, the minecraft sound engine hates this and the side effect is that the sound gets played at full volume no matter where on a server or world you are so long as the chunks are loaded serverside

**Comment by SuperNoobYT** [comment]
I know about stereo and i converted all the musics : 1 to avoid this problem, 2 to avoid a mod of 200Mo.
With 78 differents audio files, it's very likely i forgot to convert properly some of them.
So i will fix this soon if you can tell me wich sounds are in stereo it would greatly help me :D

Sorry about my english ^^'

**Comment by Redd56** [comment]
ill figure out all of them that are in stereo and post a list in a few hours, doing some other modpack dev stuff rn but will get to it in a few

**Comment by SuperNoobYT** [comment]
Weird, I tested a lot of discs and all of them are in mono. You tested them wih the resourcess packs or with the fabric mod ?
if it the ressources packs i didn't make them :/
But i will inform Yomikester238 about this problem ^^

**Comment by Redd56** [comment]
Wierd well imma test all the ones that bleed theough on phonos, cause they play at max volume no matter where in the world you are

**Comment by SuperNoobYT** [comment]
I [tested 26 différents discs](https://youtu.be/uAMjUhGZh5c), all (or almost, because i'am not sure, i only tested 1/3 of the discs) the mod's discs are in mono and all the discs in the ressources packs are in stereo.
I didn't understand why are you speaking about phonos i know it's a mods but i never used it and i don't understand the link with my mod ?

**Comment by Redd56** [comment]
let me fire up an instance and test each one

**Comment by Redd56** [comment]
it would appear as tho i somehow idk how mixed your mod up with another. how the hell did i manage that,

**Comment by Redd56** [comment]
sorry bout the confusion.
